
sequenceDiagram
    participant Cust as CustomerSupportAgent
    participant Orch as OrchestratorAgent
    participant Ord as OrderAgent
    participant Quote as QuoteAgent
    participant Inv as InventoryAgent
    actor Customer

    Note right of Cust: Categories requests,<br/>Order<br/>Quote<br/>Inventory
    Cust->>Orch: Categorised requests
    par Delegate Agent
        Note right of Orch: Delegate Agents
        Orch-->>Ord: Order requests
        Orch-->>Quote: Quotation requests
        Orch-->>Inv: Inventory requests
    and Confirm response meets criteria
        Ord-->>Orch: Order confirmation
        Quote-->>Orch: Quotation(s)
        Inv-->>Orch: Inventory List
        Orch->>Cust: Results of the requests
    end
    loop Until satisified
        Customer->>Cust: send requests
    end
    Customer-->>Cust: requests statisfied
