[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Multi-Agents-Customer-Support"
version = "0.1.0"
description = "Beavers Paper Company"
authors = [{name = "Idris"}]
requires-python = ">=3.13"

[tool.setuptools.packages.find]
include = ["utils*", "lib*"]

[tool.pytest.ini_options]
pythonpath = "."

[tool.flake8]
max-line-length = 79
exclude = [".venv", "build/lib", ".git", "__pycache__", ".env", ".pytest_cache"]
