name: imc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - requests=2.31
  - pip
  - pip:
    - torch
    - torchvision
    - typer
    - rich