[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imc"
version = "0.1.0"
description = "imc is an image classifier using deep neural network"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Eedy Green", email = "eedygreen@outlook.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Langugae :: Python :: 3",
    "Operating System :: OS Independent",
    "Artificial Intelligence :: Deep Neural Network",
]
dependencies = [
    "torch ",
    "torchvision",
    "numpy",
]

[tools.setuptools.packages.find]
where = ["src"]
include = ["imc*", "condig*", "middleware*", "processor*", "utils*"]

[project.scripts]
imc = "imc.command:app"